DROP TABLE IF EXISTS counters;
CREATE TABLE IF NOT EXISTS counters (
    id INTEGER PRIMARY KEY NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    num INTEGER NOT NULL DEFAULT(0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);
